service: serverless-example

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  - serverless-plugin-include-dependencies

functions:
  hello:
    handler: src/server.handler 
    events:
      - http:
          path: /
          method: get
      - http:
          path: /hello
          method: get
