service: serverless-example

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

functions:
  hello:
    handler: src/server.handler 
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
